/**
 * Seed data — populates localStorage on first admin login so the panel has
 * something to display before the NestJS API + Netsis sync are wired in.
 *
 * Idempotent: only seeds if storage is empty for that key.
 */
import type {
  Product,
  Order,
  Dealer,
  StockReservation,
  StockSyncStatus,
  LogisticsRule,
  Popup,
  NotifyRequest,
  SiteSettings,
  AuditLogEntry,
} from '~/types'
import { storage, uid } from './storage'

const now = new Date()
const daysAgo = (n: number) => new Date(now.getTime() - n * 86_400_000).toISOString()

// ───── Products ──────────────────────────────────────────────────────────────
const seedProducts: Product[] = [
  {
    id: 'prd_001',
    netsisCode: 'AKG-60120-EVB',
    sku: '60X120N-PK-LF-EVB',
    name: '60X120N PK LF EVEREST BEIGE',
    brand: 'AKGÜN',
    category: 'Granit Seramik',
    description: 'Rektifiyeli, lappato finish, 1.4m² kutu',
    images: ['/products/everest-beige.jpg'],
    basePrice: 320,
    taxRate: 0.2,
    unit: 'm²',
    visible: true,
    purchasable: true,
    netsisStock: 482,
    reservedStock: 24,
    displayStock: 458,
    minimumStock: 10,
    middleStock: 100,
    lastNetsisSync: daysAgo(0),
    syncStatus: 'synced',
    variations: [],
    createdAt: daysAgo(60),
    updatedAt: daysAgo(0),
  },
  {
    id: 'prd_002',
    netsisCode: 'AKG-60120-NVS',
    sku: '60X120N-PK-LF-NVS',
    name: '60X120N PK LF NAVAS SİYAH',
    brand: 'AKGÜN',
    category: 'Granit Seramik',
    description: 'Mat finish siyah granit',
    images: ['/products/navas-siyah.jpg'],
    basePrice: 315,
    taxRate: 0.2,
    unit: 'm²',
    visible: true,
    purchasable: true,
    netsisStock: 218,
    reservedStock: 0,
    displayStock: 218,
    minimumStock: 5,
    middleStock: 80,
    lastNetsisSync: daysAgo(0),
    syncStatus: 'synced',
    variations: [],
    createdAt: daysAgo(58),
    updatedAt: daysAgo(0),
  },
  {
    id: 'prd_003',
    netsisCode: 'AKG-30060-MRB',
    sku: '30X60-MRB-WH',
    name: '30X60 MERMER BEYAZ',
    brand: 'AKGÜN',
    category: 'Duvar Karosu',
    description: 'Damarlı mermer görünümlü duvar karosu',
    images: [],
    basePrice: 145,
    taxRate: 0.2,
    unit: 'm²',
    visible: true,
    purchasable: false, // visible but cannot purchase (e.g., out of stock)
    netsisStock: 4,
    reservedStock: 4,
    displayStock: 0,
    minimumStock: 20,
    middleStock: 60,
    lastNetsisSync: daysAgo(0),
    syncStatus: 'synced',
    variations: [],
    createdAt: daysAgo(120),
    updatedAt: daysAgo(0),
  },
  {
    id: 'prd_004',
    netsisCode: 'AKG-80080-CAR',
    sku: '80X80-CAR-GR',
    name: '80X80 CARRARA GRİ',
    brand: 'AKGÜN',
    category: 'Granit Seramik',
    description: 'Polished, 1.28m² kutu',
    images: [],
    basePrice: 410,
    taxRate: 0.2,
    unit: 'm²',
    visible: true,
    purchasable: true,
    netsisStock: 67,
    reservedStock: 12,
    displayStock: 55,
    minimumStock: 8,
    middleStock: 40,
    lastNetsisSync: daysAgo(0),
    syncStatus: 'pending',
    variations: [],
    createdAt: daysAgo(40),
    updatedAt: daysAgo(0),
  },
  {
    id: 'prd_005',
    netsisCode: 'AKG-FUGA-GR',
    sku: 'FUGA-2KG-GR',
    name: 'FUGA DOLGU 2KG GRİ',
    brand: 'AKGÜN',
    category: 'Yardımcı Ürünler',
    description: 'Çimentolu fuga dolgu malzemesi',
    images: [],
    basePrice: 85,
    taxRate: 0.2,
    unit: 'adet',
    visible: false, // hidden from catalog
    purchasable: false,
    netsisStock: 0,
    reservedStock: 0,
    displayStock: 0,
    minimumStock: 5,
    middleStock: 30,
    lastNetsisSync: daysAgo(2),
    syncStatus: 'error',
    variations: [],
    createdAt: daysAgo(200),
    updatedAt: daysAgo(2),
  },
]

// ───── Dealers ───────────────────────────────────────────────────────────────
const seedDealers: Dealer[] = [
  {
    id: 'dlr_001',
    name: 'Ankara Yapı Malzemeleri Ltd.',
    contactPerson: 'Mehmet Yılmaz',
    email: 'info@ankarayapi.com',
    phone: '+90 312 555 0001',
    cariNo: '120.01.0001',
    cariValidated: true,
    taxNo: '1234567890',
    taxOffice: 'Çankaya',
    city: 'Ankara',
    region: 'icAnadolu',
    address: 'OSTİM OSB, 100. Yıl Cad. No:45',
    status: 'active',
    cariBalance: -45_000,
    creditLimit: 100_000,
    totalOrders: 12,
    totalRevenue: 145_000,
    lastOrderAt: daysAgo(2),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(2),
  },
  {
    id: 'dlr_002',
    name: 'İzmir Ticaret A.Ş.',
    contactPerson: 'Ayşe Demir',
    email: 'iletisim@izmirticaret.com.tr',
    phone: '+90 232 555 0002',
    cariNo: '120.01.0002',
    cariValidated: true,
    taxNo: '0987654321',
    taxOffice: 'Konak',
    city: 'İzmir',
    region: 'ege',
    address: 'Bornova, Ankara Cad. No:128',
    status: 'active',
    cariBalance: -12_500,
    creditLimit: 75_000,
    totalOrders: 8,
    totalRevenue: 87_300,
    lastOrderAt: daysAgo(5),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(5),
  },
  {
    id: 'dlr_003',
    name: 'İstanbul Yapı Market',
    contactPerson: 'Kemal Aydın',
    email: 'kemal@istanbulyapi.com',
    phone: '+90 212 555 0003',
    cariNo: '120.01.0003',
    cariValidated: false, // pending Netsis match
    taxNo: '5544332211',
    taxOffice: 'Beylikdüzü',
    city: 'İstanbul',
    region: 'marmara',
    address: 'Beylikdüzü OSB',
    status: 'pending',
    cariBalance: 0,
    creditLimit: 0,
    totalOrders: 0,
    totalRevenue: 0,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'dlr_004',
    name: 'Bursa İnşaat Malz.',
    contactPerson: 'Hakan Şen',
    email: 'hakan@bursainsaat.com',
    phone: '+90 224 555 0004',
    cariNo: '120.01.0004',
    cariValidated: true,
    taxNo: '1122334455',
    taxOffice: 'Osmangazi',
    city: 'Bursa',
    region: 'marmara',
    address: 'NOSAB, 5.Cad. No:12',
    status: 'active',
    cariBalance: 8_200, // alacak (we owe them — return/credit note)
    creditLimit: 50_000,
    totalOrders: 5,
    totalRevenue: 42_100,
    lastOrderAt: daysAgo(14),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(14),
  },
  {
    id: 'dlr_005',
    name: 'Antalya Karo Center',
    contactPerson: 'Selin Kara',
    email: 's.kara@antalyakaro.com',
    phone: '+90 242 555 0005',
    cariNo: '120.01.0005',
    cariValidated: true,
    taxNo: '9988776655',
    taxOffice: 'Muratpaşa',
    city: 'Antalya',
    region: 'akdeniz',
    address: 'Kepez Sanayi',
    status: 'inactive', // suspended for non-payment
    cariBalance: -78_400,
    creditLimit: 60_000,
    totalOrders: 22,
    totalRevenue: 312_000,
    lastOrderAt: daysAgo(45),
    createdAt: daysAgo(365),
    updatedAt: daysAgo(30),
  },
]

// ───── Orders ────────────────────────────────────────────────────────────────
const seedOrders: Order[] = [
  {
    id: 'ord_001',
    orderNo: 'SDK-2026-0001',
    customerType: 'B2B',
    customerId: 'dlr_001',
    customerName: 'Ankara Yapı Malzemeleri Ltd.',
    dealerId: 'dlr_001',
    dealerCariNo: '120.01.0001',
    shippingCity: 'Ankara',
    shippingAddress: 'OSTİM OSB, 100. Yıl Cad. No:45',
    status: 'pending-approval',
    lines: [
      {
        id: uid('ln'),
        productId: 'prd_001',
        productName: '60X120N PK LF EVEREST BEIGE',
        sku: '60X120N-PK-LF-EVB',
        quantity: 24,
        unitPrice: 320,
        taxRate: 0.2,
        total: 24 * 320 * 1.2,
      },
    ],
    subtotal: 7680,
    tax: 1536,
    logisticsSurcharge: 450,
    total: 9666,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: 'ord_002',
    orderNo: 'SDK-2026-0002',
    customerType: 'B2C',
    customerId: 'usr_001',
    customerName: 'Ahmet Çelik',
    shippingCity: 'İstanbul',
    shippingAddress: 'Kadıköy, Bağdat Cad. No:42',
    status: 'completed',
    lines: [
      {
        id: uid('ln'),
        productId: 'prd_002',
        productName: '60X120N PK LF NAVAS SİYAH',
        sku: '60X120N-PK-LF-NVS',
        quantity: 6,
        unitPrice: 315,
        taxRate: 0.2,
        total: 6 * 315 * 1.2,
      },
    ],
    subtotal: 1890,
    tax: 378,
    logisticsSurcharge: 0,
    total: 2268,
    eInvoiceNo: 'GIB2026000010023',
    eInvoiceStatus: 'accepted',
    eIrsaliyeNo: 'IRS2026000234',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(0),
  },
  {
    id: 'ord_003',
    orderNo: 'SDK-2026-0003',
    customerType: 'B2B',
    customerId: 'dlr_002',
    customerName: 'İzmir Ticaret A.Ş.',
    dealerId: 'dlr_002',
    dealerCariNo: '120.01.0002',
    shippingCity: 'İzmir',
    shippingAddress: 'Bornova, Ankara Cad. No:128',
    status: 'shipped',
    lines: [
      {
        id: uid('ln'),
        productId: 'prd_004',
        productName: '80X80 CARRARA GRİ',
        sku: '80X80-CAR-GR',
        quantity: 12,
        unitPrice: 410,
        taxRate: 0.2,
        total: 12 * 410 * 1.2,
      },
    ],
    subtotal: 4920,
    tax: 984,
    logisticsSurcharge: 320,
    total: 6224,
    eInvoiceNo: 'GIB2026000010019',
    eInvoiceStatus: 'submitted',
    eIrsaliyeNo: 'IRS2026000231',
    approvedBy: '1',
    approvedAt: daysAgo(2),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
  {
    id: 'ord_004',
    orderNo: 'SDK-2026-0004',
    customerType: 'B2B',
    customerId: 'dlr_004',
    customerName: 'Bursa İnşaat Malz.',
    dealerId: 'dlr_004',
    dealerCariNo: '120.01.0004',
    shippingCity: 'Bursa',
    shippingAddress: 'NOSAB, 5.Cad. No:12',
    status: 'pending-approval',
    lines: [
      {
        id: uid('ln'),
        productId: 'prd_001',
        productName: '60X120N PK LF EVEREST BEIGE',
        sku: '60X120N-PK-LF-EVB',
        quantity: 100,
        unitPrice: 320,
        taxRate: 0.2,
        total: 100 * 320 * 1.2,
      },
    ],
    subtotal: 32000,
    tax: 6400,
    logisticsSurcharge: 800,
    total: 39200,
    notes: 'Acil teslimat talebi var',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
]

// ───── Stock reservations ────────────────────────────────────────────────────
const seedReservations: StockReservation[] = [
  {
    id: uid('rsv'),
    productId: 'prd_001',
    productName: '60X120N PK LF EVEREST BEIGE',
    orderId: 'ord_001',
    orderNo: 'SDK-2026-0001',
    dealerId: 'dlr_001',
    dealerName: 'Ankara Yapı Malzemeleri Ltd.',
    quantity: 24,
    status: 'active',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
  {
    id: uid('rsv'),
    productId: 'prd_004',
    productName: '80X80 CARRARA GRİ',
    orderId: 'ord_003',
    orderNo: 'SDK-2026-0003',
    dealerId: 'dlr_002',
    dealerName: 'İzmir Ticaret A.Ş.',
    quantity: 12,
    status: 'fulfilled',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
  },
]

const seedSyncStatus: StockSyncStatus = {
  lastSyncAt: daysAgo(0),
  lastSyncDuration: 12_400,
  productsSynced: 4000,
  errors: 1,
  status: 'success',
  nextScheduledAt: new Date(now.getTime() + 60 * 60 * 1000).toISOString(),
}

// ───── Logistics rules ───────────────────────────────────────────────────────
const seedLogistics: LogisticsRule[] = [
  {
    id: 'lg_marmara',
    region: 'marmara',
    cities: ['İstanbul', 'Bursa', 'Kocaeli', 'Sakarya', 'Tekirdağ', 'Edirne', 'Kırklareli', 'Yalova', 'Bilecik', 'Çanakkale', 'Balıkesir'],
    baseSurcharge: 250,
    perKgSurcharge: 0,
    perM2Surcharge: 8,
    freeShippingThreshold: 50_000,
    active: true,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: 'lg_ege',
    region: 'ege',
    cities: ['İzmir', 'Manisa', 'Aydın', 'Denizli', 'Muğla', 'Uşak', 'Afyon', 'Kütahya'],
    baseSurcharge: 320,
    perKgSurcharge: 0,
    perM2Surcharge: 10,
    freeShippingThreshold: 60_000,
    active: true,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: 'lg_icanadolu',
    region: 'icAnadolu',
    cities: ['Ankara', 'Konya', 'Kayseri', 'Eskişehir', 'Sivas', 'Yozgat', 'Çankırı', 'Kırıkkale', 'Aksaray', 'Karaman', 'Niğde', 'Nevşehir', 'Kırşehir'],
    baseSurcharge: 450,
    perKgSurcharge: 0,
    perM2Surcharge: 12,
    freeShippingThreshold: 75_000,
    active: true,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: 'lg_akdeniz',
    region: 'akdeniz',
    cities: ['Antalya', 'Adana', 'Mersin', 'Hatay', 'Osmaniye', 'Kahramanmaraş', 'Isparta', 'Burdur'],
    baseSurcharge: 550,
    perKgSurcharge: 0,
    perM2Surcharge: 14,
    freeShippingThreshold: 75_000,
    active: true,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: 'lg_karadeniz',
    region: 'karadeniz',
    cities: ['Samsun', 'Trabzon', 'Ordu', 'Giresun', 'Rize', 'Artvin', 'Sinop', 'Bartın', 'Karabük', 'Zonguldak', 'Düzce', 'Bolu', 'Kastamonu', 'Çorum', 'Amasya', 'Tokat', 'Bayburt', 'Gümüşhane'],
    baseSurcharge: 600,
    perKgSurcharge: 0,
    perM2Surcharge: 15,
    active: true,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: 'lg_doguanadolu',
    region: 'doguAnadolu',
    cities: ['Erzurum', 'Erzincan', 'Ağrı', 'Kars', 'Iğdır', 'Ardahan', 'Van', 'Bitlis', 'Muş', 'Hakkari', 'Tunceli', 'Bingöl', 'Elazığ', 'Malatya'],
    baseSurcharge: 850,
    perKgSurcharge: 0,
    perM2Surcharge: 20,
    active: true,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
  {
    id: 'lg_guneydoguanadolu',
    region: 'guneyDoguAnadolu',
    cities: ['Gaziantep', 'Şanlıurfa', 'Diyarbakır', 'Mardin', 'Batman', 'Siirt', 'Şırnak', 'Adıyaman', 'Kilis'],
    baseSurcharge: 750,
    perKgSurcharge: 0,
    perM2Surcharge: 18,
    active: true,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(30),
  },
]

// ───── Popups ────────────────────────────────────────────────────────────────
const seedPopups: Popup[] = [
  {
    id: 'pop_001',
    title: 'Yaz Kampanyası',
    body: '<p>Tüm granit seramikte <strong>%15 indirim</strong>! Sınırlı stok.</p>',
    ctaLabel: 'Hemen İncele',
    ctaUrl: '/kategori/granit-seramik',
    audience: 'all',
    startsAt: daysAgo(2),
    endsAt: new Date(now.getTime() + 14 * 86_400_000).toISOString(),
    active: true,
    showOnceKey: 'summer-2026',
    impressions: 12_450,
    clicks: 832,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: 'pop_002',
    title: 'Bayi Bilgilendirmesi — Ankara Bölgesi',
    body: '<p>Mayıs ayı boyunca Ankara teslimatlarında ek nakliye ücreti uygulanmayacaktır.</p>',
    audience: 'dealer-specific',
    dealerIds: ['dlr_001'],
    startsAt: daysAgo(0),
    endsAt: new Date(now.getTime() + 30 * 86_400_000).toISOString(),
    active: true,
    impressions: 4,
    clicks: 0,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
]

// ───── Notify requests ───────────────────────────────────────────────────────
const seedNotify: NotifyRequest[] = [
  {
    id: uid('ntf'),
    productId: 'prd_003',
    productName: '30X60 MERMER BEYAZ',
    email: 'fatma.demir@example.com',
    isDealer: false,
    status: 'pending',
    channel: 'email',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: uid('ntf'),
    productId: 'prd_003',
    productName: '30X60 MERMER BEYAZ',
    email: 'iletisim@izmirticaret.com.tr',
    phone: '+90 232 555 0002',
    isDealer: true,
    dealerId: 'dlr_002',
    status: 'pending',
    channel: 'both',
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
  },
]

const seedSettings: SiteSettings = {
  maintenanceMode: false,
  maintenanceMessage: 'Site bakım çalışması nedeniyle kısa süreliğine kapalıdır.',
  maintenanceAllowAdmins: true,
  cartReminderEnabled: true,
  cartReminderHours: 24,
  notifyChannelDefault: 'email',
  whatsappRecipient: '+90 555 000 0000',
  netsisSyncInterval: 'hourly',
  alneoTrigger: 'order-shipped',
  siteName: 'Sadöksan',
  contactEmail: 'info@sadoksan.com',
}

const seedAudit: AuditLogEntry[] = [
  {
    id: uid('audit'),
    actorId: '1',
    actorEmail: 'admin@admin.com',
    action: 'order.approve',
    entity: 'Order',
    entityId: 'ord_003',
    diff: { status: { from: 'pending-approval', to: 'approved' } },
    createdAt: daysAgo(2),
  },
  {
    id: uid('audit'),
    actorId: '1',
    actorEmail: 'admin@admin.com',
    action: 'product.update',
    entity: 'Product',
    entityId: 'prd_003',
    diff: { purchasable: { from: true, to: false } },
    createdAt: daysAgo(1),
  },
]

// ───── Seeder ────────────────────────────────────────────────────────────────
export function seedAdminData(force = false) {
  const seeds: Array<[string, unknown]> = [
    ['products', seedProducts],
    ['orders', seedOrders],
    ['dealers', seedDealers],
    ['stock-reservations', seedReservations],
    ['stock-sync-status', seedSyncStatus],
    ['logistics-rules', seedLogistics],
    ['popups', seedPopups],
    ['notify-requests', seedNotify],
    ['settings', seedSettings],
    ['audit-log', seedAudit],
    ['pricing-overrides', []],
  ]

  for (const [key, value] of seeds) {
    const existing = storage.read<unknown[] | unknown | null>(key, null)
    const isEmpty =
      existing === null ||
      (Array.isArray(existing) && existing.length === 0)
    if (force || isEmpty) {
      storage.write(key, value)
    }
  }
}
